class booleanOperation {
  public static void main(String[] args) {
    //instance...
    boolean isJavaFun = true;
    boolean isFishTasty = false;
    System.out.println(isJavaFun);     // Outputs true...
    System.out.println(isFishTasty);   // Outputs false...
  }
}
