// utility imports...
class mathOperation4 {
  public static void main(String[] args) {
    // Scanner object...
    Scanner input = new Scanner(System.in);
    // Taking input..
    System.out.print("Enter a number: );
    // input section...
    double a = input.nextDouble(); // inputs can either be decimal or floating number..
    // math operation to verify the absolute number...
    double absValue = (double) (Math.abs(a));
    // Displaying output...
    System.out.println("Absolute value is: " +absValue);

    input.close(); // if doesn't,, resoource will be leaked...
  }
}
