// utility imports..
import java.util.Scanner;
class mathOperation1 { 
  public static void main(String[] args) {
    // Scanner object...
    Scanner input = new Scanner(System.in);
    // Taking inputs...
    System.out.println("Enter Two Number: ");
    int a = input.nextInt();  // input...
    int b = input.nextInt();  // input...
    int maximum = (int) (math.max(a,b));  // math operation to verify the maximum number between them..
    // displaying the output...
    System.out.println("The Maximum Number is: " +maximum);
    input.close(); // if doesn't,, resource will be leaked...
  }
}
