// utility imports...
class mathOperation3 {
  public static void main(String[] args) {
    // Scanner object...
    Scanner input = new Scanner(System.in);
    // taking input...
    System.out.print("Enter a number: ");
    // input section..
    double a = input.nextDouble();  // the output of the Square root will be a floating value..
    // math operation to verify the square root of the number...
    double find = (double) (Math.sqrt(a));
    // displaying output...
    System.out.println("Sqaure Root of the number is: " +find);

    input.close(); // if doesn't,, the resource will be leaked...
}
